### PR TITLE
Add support for RTL

### PR DESCRIPTION
**Pull request by JBoye**
Changes textdirection in input fields when the selected language is RTL.

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Niiiice. I'll give this a test and feedback shortly.

**Comment by JBoye** [comment]
I'm not sure if this should be configurable on each datatype - It works very well for simple datatypes, but most complex editors aren't build for RTL support, so it might be better to turn it off completely

**Comment by mattbrailsford** [comment]
Hmm, yea, just tested and it does indeed do weird things with MNTP. I don't even wanna know what happens with a grid inside, with a doc type grid editor (people are doing this).

What does the back office UI do when you switch to an alternative language for an editor?

I was pondering whether this should just apply a class, and then write some CSS (if possible) to force just input textfields to be rtl/ltr, or some JS to force the dir attribute on anything inside, but again, I don't know if that will work too well on a default level.

Guess we could add an option on the pre value, but I still think we'll hit issues when people have complex editors inside.

**Comment by JBoye** [comment]
The backoffice only changes the label, but not text direction which means punctuation are incorrect, and they cant write rtl in input fields. 

It is possible to change direction in css (based on class), so we could have an option to select method (none / class / dir)

**Comment by mattbrailsford** [comment]
Maybe try that, you could add a .rtl class, and in the css do something like .rtl input[type=text] or something and capture specific input fields to convert. My only concern is that it still won't be enough as if they open dialogs, the dialog fields wouldn't be rtl.

**Comment by JBoye** [comment]
Another way could be adding dir="auto" on all default propertyeditors / inputs fields. That way, it detects direction based on the first character.

For reference, this is how our welcome message looks now with and without the "dir" attribute
skaermbillede 2015-07-02 kl 16 34 32

**Comment by JBoye** [comment]
Unfortunately the auto value is only supported with the dir attribute, not in css

**Comment by JBoye** [comment]
Okay, I've added "RTL Behaviour" as a prevalue with these options:

**Ignore**
Default behaviour

**Use .rtl class**
Sets textdirection only on input[type=text] and textarea. Works out of the box for most stuff

**Use dir attribute**
Changes the layout to RTL which may break some editors, but it sets the correct direction for everything in the editor, including other input types, select, or <div contenteditable="true">

options

I'm actually amazed that it works very well with the grid, except RTE because it uses iframe

grid

**Comment by mattbrailsford** [comment]
I've gone ahead and merged this in but updated the prevalue attribute to express this is an experimental feature so results may vary depending on the PE being wrapped.

I guess it's better to allow some than none at all.

Thanks for the PR, and sorry it's taken so long to merge in.

**Pull request merged**
